version: '0.1.0'

services:
  h2:
    image: oscarfonts/h2
    container_name: h2-database
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers -web -webAllowOthers
    ports:
      - "8082:8082"
      - "1521:1521"

  backend:
    image: anrodenasj/backend:1.0
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - h2

  frontend:
      image: anrodenasj/frontend:1.0
      container_name: angular-frontend
      ports:
        - "80:80"
      depends_on:
        - backend