# Docker Compose configuration for Spring Boot + Angular application
#
# Usage commands:
# - docker-compose down         # Stop and remove containers
# - docker system prune -af --volumes  # Remove all images and volumes
# - docker-compose up --build   # Rebuild and start
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge